# Site settings
name: "VIDEO VENDOR からのお知らせ"
email: email
url: url
description: "かんたんCM動画作成サービス VIDEO VENDOR の、新着テンプレート、開発状況、不具合情報などをお知らせします。"
author: "Team IshiHara LLC"
title: "VIDEO VENDOR"
permalink: pretty
baseurl: /

# social
facebook:
  username: videovend

instagram:
  username: video.vendor

line:
  username: 731jmqas