# Site settings
name: "VIDEO VENDOR からのお知らせ"
email: email
url: url
description: "A blog and a portfolio"
author: "Team IshiHara LLC"
title: "VIDEO VENDOR"
permalink: pretty
baseurl: /video-vendor-status

# social
facebook:
  username: videovend

instagram:
  username: video.vendor

line:
  username: 731jmqas